# anaconda envi
name: deep
dependencies:
  - python=3.6.*   # or 2.7
  - ipython
  - colorama=0.3.9
  - cycler=0.10.0
  - decorator=4.1.2
  - entrypoints=0.2.3
  - ipykernel=4.6.1
  - ipython=6.1.0
  - ipython_genutils=0.2.0
  - ipywidgets=6.0.0
  - jedi=0.10.2
  - jinja2=2.9.6
  - jsonschema=2.6.0
  - jupyter=1.0.0
  - jupyter_client=5.1.0
  - jupyter_console=5.2.0
  - jupyter_core=4.3.0
  - matplotlib=2.0.2
  - mistune=0.7.4
  - nbconvert=5.2.1
  - nbformat=4.4.0
  - notebook=5.0.0
  - numpy=1.13.*
  - pandas=0.20.3
  - pandocfilters=1.4.2
  - path.py=10.3.1
  - pickleshare=0.7.4
  - prompt_toolkit=1.0.15
  - pygments=2.2.0
  - pyparsing=2.2.0
  - pyqt=5.6.0
  - python-dateutil=2.6.1
  - pytz=2017.2
  - qt=5.6.2
  - qtconsole=4.3.1
  - scipy=0.19.1
  - setuptools=36.4.0
  - tornado=4.5.2
  - traitlets=4.3.2
  - wcwidth=0.1.7
  - Werkzeug=0.12.2
  - widgetsnbextension=3.0.2
  - zlib=1.2.*
  - pip:
    - h5py==2.7.1
    - idna==2.6
    - Keras==2.1.1
    - Mako==1.0.7
    - Markdown==2.6.9
    - netCDF4==1.3.1
    - protobuf
    - pycuda==2017.1.1
    - pytest==3.2.2
    - pytools==2017.6
    - PyYAML==3.12
    - requests==2.13.0
    - scikit-learn==0.19.1
    - six==1.11.0
#    - tensorflow-gpu==1.4
#    - tensorflow-tensorboard==0.4.*
    - urllib3==1.22
    - wheel==0.30.0
